export const book = {
  TITLE_MIN_LENGTH: 1,
  TITLE_MAX_LENGTH: 100,
  AUTHOR_MIN_LENGTH: 1,
  AUTHOR_MAX_LENGTH: 100,
  AGE_MIN: 1,
  ISBN_LENGTH: 10,
  PRINTLENGTH_MIN_LENGTH: 1
};

export const user = {
  USERNAME_MIN_LENGTH: 3,
  USERNAME_MAX_LENGTH: 30,
  PASSWORD_MIN_LENGTH: 7,
  PASSWORD_MAX_LENGTH: 20,
  FIRSTNAME_MIN_LENGTH: 1,
  FIRSTNAME_MAX_LENGTH: 20,
  LASTNAME_MIN_LENGTH: 1,
  LASTNAME_MAX_LENGTH: 20,
  AGE_MIN: 0
};

export const review = {
  TEXT_MIN_LENGTH: 10,
  TEXT_MAX_LENGTH: 300
};
