export const book = {
  TITLE_MIN_LENGTH: 1,
  TITLE_MAX_LENGTH: 100,
  AUTHOR_MIN_LENGTH: 1,
  AUTHOR_MAX_LENGTH: 100,
  AGE_MIN: 1,
};

export const user = {
  USERNAME_MIN_LENGTH: 3,
  USERNAME_MAX_LENGTH: 20,
  PASSWORD_MIN_LENGTH: 4,
  PASSWORD_MAX_LENGTH: 30,
};

export const review = {
  CONTENT_MIN_LENGTH: 10,
  CONTENT_MAX_LENGTH: 300,
};
